version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose Nginx on port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # Mount the custom Nginx config
      - ./persistent_data/uploaded_images:/usr/share/nginx/html  # Serve static files from this directory
    depends_on:
      - backend
    restart: always

  backend:
    image: syncup/backend:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/syncup
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EXTERNAL_API_LOCALIMAGESERVICE_ENDPOINT: http://image-upload-service:8081
      EXTERNAL_API_LOCALIMAGESERVICE_HOSTEDPREFIX: http://localhost/images
    depends_on:
      - db
      - image-upload-service
  
  image-upload-service:
    image: syncup/image-upload-service:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/imagemanagementservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      FILES_BASE-DIRECTORY: "/images"
    volumes:
      - ./persistent_data/uploaded_images:/images
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - ./persistent_data/postgres-data:/var/lib/postgresql/data
      - ./init-scripts/db:/docker-entrypoint-initdb.d/
